config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  mount Sidekiq::Web => '/sidekiq'

  if Rails.configuration.x.cypress
    namespace :cypress do
      delete 'cleanup', to: 'cleanup#destroy'
    end
  end

  resources :clicks, only: %i[index create]

  get '/manifest.v1.webmanifest', to: 'statics#manifest', as: :webmanifest

  root to: 'vue#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/click.rb
class Click < ApplicationRecord
  validates :ip, presence: true
  validates :user_agent, presence: true

  # There is no `updated_at` in the database
  def updated_at
    created_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  def index
    clicks = Click.order(created_at: :desc).limit(5).to_a
    return unless stale?(clicks, template: false, public: true)

    expires_in 0, must_revalidate: true

    respond_to do |format|
      format.json { render json: { total: Click.count, items: clicks } }
    end
  end

  def create
    click =
      Click.create! user_agent: request.user_agent,
                    ip: anonymize(request.remote_ip)
    ActionCable.server.broadcast 'clicks_channel', click
  end

  private

  def anonymize(ip)
    addr = IPAddr.new(ip.to_s)
    if addr.ipv4?
      # set last octet to 0
      addr.mask(24)
    else
      # set last 80 bits to zeros
      addr.mask(48)
    end
  end
end

app/controllers/cypress/cleanup_controller.rb
module Cypress
  class CleanupController < ActionController::Base
    skip_before_action :verify_authenticity_token

    def destroy
      return unless Rails.configuration.x.cypress

      tables = ActiveRecord::Base.connection.tables
      tables.delete 'schema_migrations'
      tables.each do |t|
        ActiveRecord::Base.connection.execute("TRUNCATE #{t} CASCADE")
      end

      head :ok
    end
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def manifest
    expires_in 1.day

    respond_to { |format| format.webmanifest { render } }
  end
end

app/controllers/vue_controller.rb
class VueController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def versions
    {
      alpine: alpine_version,
      ruby: ruby_version,
      rails: rails_version,
      puma: puma_version,
      postgres: postgres_version,
      redis: redis_version,
      sidekiq: sidekiq_version,
    }
  end

  private

  def alpine_version
    return unless RUBY_PLATFORM.include?('linux')

    `cat /etc/alpine-release 2>/dev/null`.chomp
  end

  def ruby_version
    RUBY_VERSION
  end

  def rails_version
    Rails.version
  end

  def puma_version
    Puma::Const::PUMA_VERSION
  end

  def postgres_version
    ActiveRecord::Base.connection.select_value('SHOW server_version;')
  end

  def redis_version
    Redis.new.info['redis_version']
  end

  def sidekiq_version
    Sidekiq::VERSION
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Templatus-Vue</title>

    <meta name="description" content="Ruby on Rails template for using Vue.js 3">

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Templatus (Vue edition)">
    <meta name="theme-color" content="#991c1c">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Templatus (Vue edition)">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="msapplication-TileColor" content="#ffc40d">

    <meta name="git-commit-version" content="<%= Rails.configuration.x.git.commit_version %>">
    <meta name="git-commit-time" content="<%= Rails.configuration.x.git.commit_time %>">

    <% if Rails.configuration.x.honeybadger.api_key %>
    <meta name="honeybadger-api-key" content="<%= Rails.configuration.x.honeybadger.api_key %>">
    <% end %>

    <% if Rails.configuration.x.plausible_url %>
    <meta name="plausible-url" content= "<%= Rails.configuration.x.plausible_url %>">
    <% end %>
    <% if Rails.configuration.x.app_host %>
    <meta name="app-host" content= "<%= Rails.configuration.x.app_host %>">
    <% end %>

    <% if Rails.configuration.asset_host.present? %>
    <meta name="asset-host" content="<%= request.protocol %><%= Rails.configuration.asset_host %>">
    <% end %>

    <% cache Rails.configuration.x.git.commit_version do %>
      <% versions.each do |name, version| %>
        <%= tag.meta name: "version-#{name}", content: version %>
      <% end %>
    <% end %>

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= tag :link, href: asset_path('/apple-touch-icon.png'), rel: 'apple-touch-icon', type: 'image/png', sizes: '180x180' %>
    <%= tag :link, href: asset_path('/favicon-32x32.png'),    rel: 'icon',             type: 'image/png', sizes: '32x32' %>
    <%= tag :link, href: asset_path('/favicon-16x16.png'),    rel: 'icon',             type: 'image/png', sizes: '16x16' %>
    <%= tag :link, href: asset_path('/safari-pinned-tab.svg'),rel: 'mask-icon',        color: '#d30001' %>
    <%= tag :link, href: webmanifest_path, rel: 'manifest' %>
    <%= tag :link, href: vite_asset_path('images/logo.svg'), rel: 'preload', as: 'image' %>

    <%= vite_client_tag %>
    <%= vite_typescript_tag 'application' %>
    <%= vite_stylesheet_tag 'application' %>
  </head>

  <body>
    <noscript>
      <p>This website doesn't work without JavaScript enabled. Please enable it to continue.</p>
    </noscript>

    <%= yield %>
  </body>
</html>

app/views/statics/manifest.webmanifest.erb
{
  "name": "Templatus (Vue edition)",
  "short_name": "Templatus",
  "start_url": "/",
  "display": "standalone",
  "orientation": "portrait",
  "icons": [
    {
      "src": "<%= asset_path('/android-chrome-192x192.png') %>",
      "sizes": "192x192",
      "type": "image/png"
    },
    {
      "src": "<%= asset_path('/android-chrome-512x512.png') %>",
      "sizes": "512x512",
      "type": "image/png"
    },
    {
      "src": "<%= asset_path('/maskable_icon_x384.png') %>",
      "sizes": "384x384",
      "type": "image/png",
      "purpose": "maskable"
    }
  ],
  "theme_color": "#991c1c",
  "background_color": "#ffffff"
}

app/views/vue/index.html.erb
<div id='vue-app'></div>